// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/repo.go

// Package repo is a generated GoMock package.
package repo

import (
	reflect "reflect"

	types "github.com/AbsaOSS/tf-provider-registry-generator/internal/types"
	gomock "github.com/golang/mock/gomock"
	github "github.com/google/go-github/github"
)

// MockIRepo is a mock of IRepo interface.
type MockIRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIRepoMockRecorder
}

// MockIRepoMockRecorder is the mock recorder for MockIRepo.
type MockIRepoMockRecorder struct {
	mock *MockIRepo
}

// NewMockIRepo creates a new mock instance.
func NewMockIRepo(ctrl *gomock.Controller) *MockIRepo {
	mock := &MockIRepo{ctrl: ctrl}
	mock.recorder = &MockIRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepo) EXPECT() *MockIRepoMockRecorder {
	return m.recorder
}

// Clone mocks base method.
func (m *MockIRepo) Clone() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone")
	ret0, _ := ret[0].(error)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockIRepoMockRecorder) Clone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockIRepo)(nil).Clone))
}

// CommitAndPush mocks base method.
func (m *MockIRepo) CommitAndPush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitAndPush")
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitAndPush indicates an expected call of CommitAndPush.
func (mr *MockIRepoMockRecorder) CommitAndPush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitAndPush", reflect.TypeOf((*MockIRepo)(nil).CommitAndPush))
}

// GetAssets mocks base method.
func (m *MockIRepo) GetAssets(arg0 string, arg1 []*github.RepositoryRelease) (*types.FileAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssets", arg0, arg1)
	ret0, _ := ret[0].(*types.FileAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssets indicates an expected call of GetAssets.
func (mr *MockIRepoMockRecorder) GetAssets(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssets", reflect.TypeOf((*MockIRepo)(nil).GetAssets), arg0, arg1)
}

// GetReleases mocks base method.
func (m *MockIRepo) GetReleases() ([]*github.RepositoryRelease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReleases")
	ret0, _ := ret[0].([]*github.RepositoryRelease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReleases indicates an expected call of GetReleases.
func (mr *MockIRepoMockRecorder) GetReleases() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReleases", reflect.TypeOf((*MockIRepo)(nil).GetReleases))
}
