// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/storage.go

// Package storage is a generated GoMock package.
package storage

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/k0da/tfreg-golang/internal/types"
)

// MockStorage is a mock of IStorage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetVersions mocks base method.
func (m *MockStorage) GetVersions() (types.Versions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersions")
	ret0, _ := ret[0].(types.Versions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersions indicates an expected call of GetVersions.
func (mr *MockStorageMockRecorder) GetVersions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersions", reflect.TypeOf((*MockStorage)(nil).GetVersions))
}

// WritePlatformMetadata mocks base method.
func (m *MockStorage) WritePlatformMetadata(download types.Download) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePlatformMetadata", download)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WritePlatformMetadata indicates an expected call of WritePlatformMetadata.
func (mr *MockStorageMockRecorder) WritePlatformMetadata(download interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePlatformMetadata", reflect.TypeOf((*MockStorage)(nil).WritePlatformMetadata), download)
}

// WriteVersions mocks base method.
func (m *MockStorage) WriteVersions(v types.Versions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteVersions", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteVersions indicates an expected call of WriteVersions.
func (mr *MockStorageMockRecorder) WriteVersions(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteVersions", reflect.TypeOf((*MockStorage)(nil).WriteVersions), v)
}
