// Code generated by MockGen. DO NOT EDIT.
// Source: internal/terraform/terraform.go

// Package terraform is a generated GoMock package.
package terraform

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/k0da/tfreg-golang/internal/types"
)

// MockITerraform is a mock of ITerraform interface.
type MockITerraform struct {
	ctrl     *gomock.Controller
	recorder *MockITerraformMockRecorder
}

// MockITerraformMockRecorder is the mock recorder for MockITerraform.
type MockITerraformMockRecorder struct {
	mock *MockITerraform
}

// NewMockITerraform creates a new mock instance.
func NewMockITerraform(ctrl *gomock.Controller) *MockITerraform {
	mock := &MockITerraform{ctrl: ctrl}
	mock.recorder = &MockITerraformMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITerraform) EXPECT() *MockITerraformMockRecorder {
	return m.recorder
}

// GenerateTerraformJSON mocks base method.
func (m *MockITerraform) GenerateTerraformJSON() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTerraformJSON")
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateTerraformJSON indicates an expected call of GenerateTerraformJSON.
func (mr *MockITerraformMockRecorder) GenerateTerraformJSON() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTerraformJSON", reflect.TypeOf((*MockITerraform)(nil).GenerateTerraformJSON))
}

// GenerateVersion mocks base method.
func (m *MockITerraform) GenerateVersion() *types.Version {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateVersion")
	ret0, _ := ret[0].(*types.Version)
	return ret0
}

// GenerateVersion indicates an expected call of GenerateVersion.
func (mr *MockITerraformMockRecorder) GenerateVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateVersion", reflect.TypeOf((*MockITerraform)(nil).GenerateVersion))
}

// GetDownloadInfo mocks base method.
func (m *MockITerraform) GetDownloadInfo() ([]types.Download, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadInfo")
	ret0, _ := ret[0].([]types.Download)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDownloadInfo indicates an expected call of GetDownloadInfo.
func (mr *MockITerraformMockRecorder) GetDownloadInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadInfo", reflect.TypeOf((*MockITerraform)(nil).GetDownloadInfo))
}
